# Embedded file name: otp.speedchat.SCDecoders
from SCStaticTextTerminal import decodeSCStaticTextMsg
from SCCustomTerminal import decodeSCCustomMsg
from SCEmoteTerminal import decodeSCEmoteWhisperMsg